# Vietnamese translation
# vim: ft=jthuộc tính

general=Tổng thể
language:=ngôn ngữ:
hebrew=Tiếng Hebrơ
arabic=Tiếng Ả Rập

textMessage:=Please note: Do not enter the same word into the storage more than once.

returnIncorrectToStorage:=Đưa lỗi về bộ nhớ:
workSurface=vùng thao tác

distractor=Tùy chọn
media=tĩnh
group=nhóm

distractors=tùy chọn
groups=Các nhóm

stageTooltip=
stageTooltip.innerHTML=<p>Sử dụng menu phía trên để chọn lựa giữa các Yếu Tố Gây Xao Nhãng, tĩnh hoặc Nhóm.</p><p>Nhấp vào vùng thao tác để tạo ra đối tượng mới</p>

freeGroup:=vị trí phụ tá:
freeGroupFalse:=định nghĩa
freeGroupTrue:=Miễn phí

uploadImage=Đăng tải

background:=Nền:
color=Màu sắc

transparent=Trong suốt
opaque=Bóng mờ

fontSize:=kích thước font chữ:
small=nhỏ
medium=trung bình
large=lớn

backgroundColor:=Màu nền:

finiteStorage:=Bộ nhớ có thể dùng:

storageTooltip=
storageTooltip.innerHTML=Khi chọn bộ nhớ không sử dụng được bạn có thể kéo yếu tố gây xao nhãng vài lần từ bộ nhớ vào vùng kéo.<br />Để có thể kéo cùng yếu tố gây xao nhãng sang nơi khác chúng tôi đã thêm vào một cơ chế gọi là "Associated replication". <span class="component-duplicate-linked" title="linked duplicate"></span>

text:=chữ:

textMask=
textMask.title=Vùng chữ không liên quan đến nhóm

width:=Chiều rộng
height:=Chiều cao:         
distanceFromTop:=bên trên:
distanceFromLeft:=bên trái:

commonFeatures=các tính chất phổ biến

duplicateBtn=
duplicateBtn.title=Nhân đôi

duplicateLinkedBtn=
duplicateLinkedBtn.title=Bản sao có liên kết

propertiesDisableMask=
propertiesDisableMask.title=Chọn một yếu tố gây xao nhãng để kích hoạt các vùng cho việc biên tập 

isDistractingOption=mất tập trung gây hiểu lầm

border:=Biên:
noBorder=Không biên

myStudio=myStudio

# Alerts
removeDestructorsError=Bỏ các bản sao có liên kết để dời sang bộ nhớ có thể dùng
inputTwoDestructorsError=Xin nhập vào ít nhất hai yếu tố gây xao nhãng.
emptyGroupError=Xin nhập vào ít nhất một đối tượng cho mỗi nhóm.
hiddenBasketInGroupError=Đừng tạo ra sai lệch đánh lạc Nhóm.
inputInvalidBasketName=Invalid characters entered. Please check and correct the text.