# Hebrew translation
# vim: ft=jproperties

general=عامّ 
language:=اللغة:
hebrew=العبرية
arabic=العربيّة

textMessage:=انتبهوا! لا يجوز إدخال الكلمة نفسها إلى المخزن أكثر من مرّة.

returnIncorrectToStorage:=إعادة الخطّا إلى المخزن:
workSurface=سطح العمل

distractor=خيار
media=وسيط
group=مجموعة

distractors=خيارات 
groups=مجموعات

stageTooltip=
stageTooltip.innerHTML=انقروا على كلّ مكان في مسطّح العمل لإنشاء مبنًى جديد</p><p> لاختيار التشكيل المناسب يجب استخدام القائمة العليا
 
uploadImage=ارفعوا صورة

background:=خلفيّة:
color=لون

transparent=شفّاف
opaque=غير شفّاف

fontSize:=حجم الخطّ
small=صغير 
medium=متوسّط
large=كبير

backgroundColor:=بون الخلفيّة:

finiteStorage:=مخزن قابل للنفاد:

storageTooltip=
storageTooltip.innerHTML=בבחירת אפשרות של מחסן לא מתכלה ניתן לגרור את אותו מסיח מספר פעמים מהמחסן לאיזור הגרירה.<br />בכדי לאפשר גרירה של אותו מסיח למקומות שונים הוספנו יכולת בשם "שכפול כמקושר". <span class="component-duplicate-linked" title="نسخ كأنّه مع رابط"></span>

freeGroup=مكان الخيارات بالمجموعة:
freeGroupFalse=معرف مسبقا
freeGroupTrue=حر

text:=نصّ:

textMask=
textMask.title=خانة النصّ لا صلة لها بالمجموعات

width:=العرض:
height:=الارتفاع:         
distanceFromTop:=المسافة من الأعلىّ:
distanceFromLeft:=المسافة من اليسار:

commonFeatures=صفات مشتركة

duplicateBtn=
duplicateBtn.title=نسخ

duplicateLinkedBtn=
duplicateLinkedBtn.title=النسخ كرابط

propertiesDisableMask=
propertiesDisableMask.title=يجب التأشير على خيار لتمكين تحرير الخانات

isDistractingOption=خيار مضلل

border:=إطار:

noBorder=بلا إطار

myStudio=الأستوديو الخاصّ بي 

# Alerts
removeDestructorsError=يجب إزالة الخيارات ذات الروابط للانتقال إلى المخزن القابل للنفاد
inputTwoDestructorsError=يجب كتابة خيارين على الاقلّ
emptyGroupError=الرجاء إدخال خيار واحد على الأقلّ لكلّ مجموعة
hiddenBasketInGroupError=الرجاء عدم إدخال خيار مضلل بالمجموعة.
inputInvalidBasketName=تم إدخال رموز غير صحيحة. يرجى التحقق من النص وتصحيحه.