# English translation
# vim: ft=jproperties

general=general
language:=language:
hebrew=Hebrew
arabic=Arabic

textMessage:=Please note: Do not enter the same word into the storage more than once.

returnIncorrectToStorage:=Return errors to storage:
workSurface=Working area

distractor=Distractor
media=Media
group=Group

distractors=Distractors
groups=Groups

stageTooltip=
stageTooltip.innerHTML=<p>Use the upper menu un order to choose between Distractor, Media or Group.</p><p>Click the work surface in order to create a new entity</p>

uploadImage=Upload

background:=Background:
color=Color

transparent=Transparent
opaque=Opaque

fontSize:=Font size:
small=Small
medium=Medium
large=Large

backgroundColor:=Background color:

finiteStorage:=Expendable storage:

storageTooltip=
storageTooltip.innerHTML=When choosing the option of non expendable storage you can drag the distractor a few times from the storage to the dragging area. .<br />To enable dragging the same distractor to different places we've added the capability called "Associated replication". <span class="component-duplicate-linked" title="linked duplicate"></span>

freeGroup=Distractor placement:
freeGroupFalse=Predefined
freeGroupTrue=Free

text:=text:

textMask=
textMask.title=Text field is not relevant to groups

width:=Width
height:=Height:         
distanceFromTop:=Top:
distanceFromLeft:=Left:

commonFeatures=Common properties

duplicateBtn=
duplicateBtn.title=Duplicate

duplicateLinkedBtn=
duplicateLinkedBtn.title=Associated replication

propertiesDisableMask=
propertiesDisableMask.title=Choose a distractor in order to enable the fields for editing 

isDistractingOption=Distracting option

border:=Border:
noBorder=No border

myStudio=myStudio

# Alerts
removeDestructorsError=Remove Associated replication to move to expendable storage
inputTwoDestructorsError=Please enter at least two distractors.
emptyGroupError=Please enter at least one distractor for each group.
hiddenBasketInGroupError=Please remove distracting option from groups.
inputInvalidBasketName=Invalid characters entered. Please check and correct the text.