# Hebrew translation
# vim: ft=jproperties

general=כללי
language:=שפה:
hebrew=עברית
arabic=ערבית

textMessage:=שימו לב: אין להכניס למחסן את אותה מילה יותר מפעם אחת.

returnIncorrectToStorage:=החזרת שגיאות למחסן:
workSurface=משטח העבודה

distractor=תשובה
media=מדיה
group=קבוצה

distractors=תשובות
groups=קבוצות

stageTooltip=
stageTooltip.innerHTML=<p>על מנת לבחור תשובה, מדיה או קבוצה יש להשתמש בתפריט העליון.</p><p>לחצו על משטח העבודה כדי ליצור את הישות החדשה.</p>

uploadImage=העלו תמונה

background:=רקע:
color=צבע

transparent=שקוף
opaque=אטום

fontSize:=גודל גופן:
small=קטן
medium=בינוני
large=גדול

backgroundColor:=צבע רקע:

finiteStorage:=מחסן מתכלה:

storageTooltip=
storageTooltip.innerHTML=בבחירת אפשרות של מחסן לא מתכלה ניתן לגרור את אותה תשובה מספר פעמים מהמחסן לאיזור הגרירה.<br />בכדי לאפשר גרירה של אותה תשובה למקומות שונים הוספנו יכולת בשם "שכפול כמקושר". <span class="component-duplicate-linked" title="שכפול כמקושר"></span>

freeGroup:=מיקום התשובות בקבוצה:
freeGroupFalse:=מוגדר מראש
freeGroupTrue:=חופשי

text:=טקסט:

textMask=
textMask.title=שדה טקסט אינו רלוונטי לקבוצות

width:=רוחב:
height:=גובה:         
distanceFromTop:=מרחק מלמעלה:
distanceFromLeft:=מרחק משמאל:

commonFeatures=תכונות משותפות

duplicateBtn=
duplicateBtn.title=שכפול

duplicateLinkedBtn=
duplicateLinkedBtn.title=שכפול כמקושר

propertiesDisableMask=
propertiesDisableMask.title=יש לבחור תשובה על מנת לאפשר את השדות לעריכה

isDistractingOption=תשחובה מטעה

border:=מסגרת:

noBorder=ללא מסגרת

myStudio=הסטודיו שלי

# Alerts
removeDestructorsError=יש להסיר את התשובות המקושרות על מנת לעבור למחסן מתכלה
inputTwoDestructorsError=יש להזין לפחות שתי תשובות.
emptyGroupError=יש להזין לפחות תשובה אחת בכל קבוצה.
hiddenBasketInGroupError=אין ליצור תשובה מטעה בקבוצה.
inputInvalidBasketName=הוזנו תווים לא חוקיים. אנא בדקו את הטקסט ותקנו.
