# vim: ft=jproperties


# Default language [he]
[*]
@import url(../../../../../lib/localization/globals.he.properties)
@import url(data.he.properties)


[en]
@import url(../../../../../lib/localization/globals.en.properties)
@import url(data.en.properties)



[ar]
@import url(../../../../../lib/localization/globals.ar.properties)
@import url(data.ar.properties)



[vi]
@import url(../../../../../lib/localization/globals.vi.properties)
@import url(data.vi.properties)
