# Hebrew translation
# vim: ft=jproperties

inputTextInstructions=הזינו את הטקסט, סמנו מילים לגרירה ולחצו על כפתור "הוספה למחסן המילים".
inputTextInstructions_2=שימו לב: אין להכניס למחסן את אותה מילה יותר מפעם אחת. 
font=גופן
fontSize=גודל גופן
addWord=הוספה למחסן המילים
removeWord=מחיקה ממחסן המילים

# Alerts
inputContentError=אנא הזינו תוכן בתבנית או מחקו את הפריט.
selectTwoItemsError=נא לסמן לפחות 2 פריטים