# English translation
# vim: ft=jproperties

inputTextInstructions=Enter the text, mark words for dragging and press the button 'Add word'.
inputTextInstructions_2=Please note: The same word may not be entered more than once.
font=Font
fontSize=Font size
addWord=Add word
removeWord=Remove word

# Alerts
inputContentError=No content was entered. Please add content or delete the item.
selectTwoItemsError=Please add at least 2 words to the storage. 