# Vietnamese translation
# vim: ft=jproperties

inputTextInstructions=Nhập vào chữ, đánh dấu chữ để kéo và nhấn vào nút 'Add word'
font=Font chữ
fontSize=kích thước Font
addWord=Thêm từ
removeWord=Bỏ từ

# Alerts
inputContentError=Chưa có nội dung nhập vào. Xin nhập vào nội dung hoặc xoá mục.
selectTwoItemsError=Xin thêm vào ít nhất 2 từ vào bộ nhớ. 