# Arabic translation
# vim: ft=jproperties

inputTextInstructions=اكتبوا النصّ، أشّروا على كلمات للجرّ وانقروا على زرّ"إضافة إلى مخزن الكلمات" ". 
inputTextInstructions_2=انتبهوا: لا يجوز إدخال الكلمة نفسها إلى المخزن أكثر من مرّة.
font=الخطّ
fontSize=حجم الخطّ
addWord=إضافة إلى مخزن الكلمات
removeWord=حذف من مخزن الكلمات

# Alerts
inputContentError=الرجاء إدخال المضمون.
selectTwoItemsError=الرجاء التأشير على مادّتين على الأقل