# Hebrew translation
# vim: ft=jproperties

contentDirection:=כיוון התוכן:
rightToLeft=מימין לשמאל
leftToRight=משמאל לימין

language:=שפה:
hebrew=עברית
arabic=ערבית

fontSize:=גודל גופן:
small=קטן
medium=בינוני
large=גדול

mixQuestions:=ערבול שאלות:

timeLimit:=הגבלת זמן לכל שאלה (timer):

helpers:=גלגלי הצלה:

questions:=שאלות:

addQuestionBtn=הוספת שאלה

questionPreview=צפיה בשאלה
triviaQuestion=שאלת טריויה
triviaQuestionInstuction=הזינו לפחות שני מסיחים וסמנו את התשובה הנכונה

# Alerts
notEnoughQuestionsError=יש להזין לפחות {{minNumberOfQuestions}} שאלות. הטריוויה מציגה {{numberOfShownQuestion}} שאלות ושאלה אחת היא לטובת גלגל ההצלה.
missingTextError=חסר טקסט בשאלה {{questionNumber}}
inputAtLeastTwoDistructorsError=יש להזין לפחות 2 מסיחים בשאלה {{questionNumber}}
cantSelectEmptyAnswerError=לא ניתן לסמן תשובה ריקה כנכונה בשאלה {{questionNumber}}
selectOneAnswerError=יש לסמן לפחות תשובה אחת כנכונה בשאלה {{questionNumber}}
cantUseHelpersError=לא ניתן להשתמש בגלגלי הצלה באם יש שאלה עם שני מסיחים בלבד.
removeHelpersOrAddTimerError=יש לבטל גלגלי הצלה או להוסיף תזמון למשחק, לא ניתן להוסיף גלגלי הצלה במשחק ללא תזמון
