# Vietnamese translation
# vim: ft=jproperties

contentDirection:=Chiều của nội dung:
rightToLeft=Phải sang Trái
leftToRight=Trái sang Phải

language:=Ngôn ngữ:
hebrew=Tiếng Hêbrơ
arabic=Tiếng Ả Rập

fontSize:=kích thước font:
small=Nhỏ
medium=Trung bình
large=Lớn

mixQuestions:=Tập hợp các câu hỏi:

timeLimit:=Giới hạn về thời gian:

helpers:=Giúp đỡ:

questions:=Câu hỏi:

addQuestionBtn=Thêm câu hỏi

questionPreview=Xem câu hỏi
triviaQuestion=Câu hỏi nhiều lĩnh vực
triviaQuestionInstuction=Nhập vào ít nhất 2 yếu tố gây xao nhãng và đánh dấu câu trả lời đúng 

# Alerts
notEnoughQuestionsError=Nhập vào số lượng câu hỏi {{minNumberOfQuestions}} ít nhất. Hoạt động này hiển thị {{numberOfShownQuestion}} các câu hỏi và một câu hỏi sẽ dành cho việc trả lời cho câu hỏi có sự lựa chọn nếu được yêu cầu.
missingTextError=Câu hỏi thiếu chữ {{questionNumber}}
inputAtLeastTwoDistructorsError=Nhập vào ít nhất 2 yếu tố gây xao nhãng trong câu hỏi {{questionNumber}}
cantSelectEmptyAnswerError=Bạn không thể đánh dấu câu trả lời trống là câu trả lời đúng trong câu hỏi {{questionNumber}}
selectOneAnswerError=Đánh dấu ít nhất một câu trả lời là đúng trong câu hỏi {{questionNumber}}
cantUseHelpersError=Bạn không thể sử dụng câu hỏi có sự lựa chọn nếu có một câu hỏi chỉ có 2 yếu tố gây xao nhãng
removeHelpersOrAddTimerError=Bạn không thể thêm câu hỏi có sự lựa chọn mà không có bộ tính giờ
