# Arabic translation
# vim: ft=jproperties

contentDirection:=اتّجاه المضمون:
rightToLeft=من اليمين إلى اليسار
leftToRight=من اليسار إلى اليمين

language:=اللغة:
hebrew=العبريّة
arabic=العربيّة

fontSize:=حجم الخطّ:
small=صغير 				
medium=متوسّط
large=كبير

mixQuestions:=خلط الأسئلة:

timeLimit:=تحديد الوقت لكلّ سؤال (timer):

helpers:=وسائل مساعدة:

questions:=أسئلة:

addQuestionBtn=إضافة سؤال

questionPreview=مشاهدة السؤال
triviaQuestion=سؤال معلومات عامّة
triviaQuestionInstuction=سجّلوا خيارين على الأقلّ وأشيروا إلى الإجابة الصحيحة

# Alerts
notEnoughQuestionsError=يجب كتابة {{minNumberOfQuestions}} أسئلة على الأقل. مسابقة المعلومات العامّة تعرض {{numberOfShownQuestion}} أسئلة وسؤال واحد لوسيلة المساعدة.
missingTextError=السؤال ينقصه النصّ {{questionNumber}}
inputAtLeastTwoDistructorsError=يجب تسجيل خيارين على الأقلّ في السؤال {{questionNumber}}
cantSelectEmptyAnswerError=لايمكن الإشارة إلى إجابة فارغة على أنّها إجابة صحيحة للسؤال {{questionNumber}}
selectOneAnswerError=يجب التأشير على إجابة صحيحة واحدة لكلّ سؤال {{questionNumber}}
cantUseHelpersError=لا يمكن استخدام وسائل المساعدة في سؤال إجابته من بين خيارين فقط
removeHelpersOrAddTimerError=  يجب إلغاء وسائل المساعدة أو إضافة نظام تحديد الوقت للّعبة، لا يمكن إضافة وسائل مساعدة بدون نظام لتحديد الوقت  

