# English translation
# vim: ft=jproperties

contentDirection:=Content direction:
rightToLeft=Right to Left
leftToRight=Left to Right

language:=Language:
hebrew=Hebrew
arabic=Arabic

fontSize:=font size:
small=Small
medium=Medium
large=Large

mixQuestions:=Mix of questions:

timeLimit:=Time limit:

helpers:=Help:

questions:=Questions:

addQuestionBtn=Add question

questionPreview=View question
triviaQuestion=Trivia question
triviaQuestionInstuction=Enter at least two distractors and mark the correct answer 

# Alerts
notEnoughQuestionsError=Enter at least {{minNumberOfQuestions}} questions. The activity displays {{numberOfShownQuestion}} questions and one question is for the benefit of the alternative question if requested.
missingTextError=Text is missing in question {{questionNumber}}
inputAtLeastTwoDistructorsError=Enter at least two distractors in question {{questionNumber}}
cantSelectEmptyAnswerError=You can not mark an empty answer as correct in the question {{questionNumber}}
selectOneAnswerError=Mark at least one answer as correct in question {{questionNumber}}
cantUseHelpersError=You cannot use alternative question if there is a question with only two distractors
removeHelpersOrAddTimerError=You can not add alternative question without a timer
