# Vietnamese Translation
# vim: ft=jproperties

text=chữ 
image=hình ảnh
soundFile=âm thanh

uploadImage=Đăng tải
uploadSoundFile=Đăng tải

textSettings:=Thuộc tính của chữ:
background:=nền:
color=Màu sắc
or=hoặc
image=Ảnh
deleteBackgroundImageBtn=
deleteBackgroundImageBtn.title=Xoá ảnh
transparent=Trong suốt
opaque=Bóng mờ
pairsToShow:=Số cặp:
pairSize:=Kích thước cặp:
small=Nhỏ
medium=Trung bình
large=Lớn
pairs:=Các cặp:
myStudio=myStudio
pair=Cặp
addPair=Thêm cặp


# Alerts
incorrectFileSize=Kích thước tập tin lớn hơn 1/2 Mega. Xin hãy giảm kích thước của tập tin hoặc chọn tập tin khác.
incorrectFileType=Loại tập tin không được hỗ trợ
uploadOnlyMp3=Bạn chỉ có thể tải lên tập tin loại mp3 

addSoundFileInRightFieldOfPair=Xin thêm vào tập tin âm thanh theo cặp-{{pairNumber}}
addImageFileInRightFieldOfPair=Xin thêm vào tập tin ảnh theo cặp-{{pairNumber}}
addTextInRightFieldOfPair=Xin nhập vào chữ theo cặp-{{pairNumber}}

addSoundFileInLeftFieldOfPair=Xin thêm vào tập tin âm thanh theo cặp-{{pairNumber}}
addImageFileInLeftFieldOfPair=Xin thêm vào tập tin ảnh theo cặp-{{pairNumber}}
addTextInLeftFieldOfPair=Xin nhập vào chữ theo cặp-{{pairNumber}}

pairsNumberToShowIsTooBig=Số lượng cặp mà bạn chọn cho phép hiển thị lớn hơn số lượng cặp bạn đã nhập 

minNumberOfPairs=Xin nhập vào số cặp {{minNumber}} ít nhất.