# English translation
# vim: ft=jproperties

text=Text 
image=Image
soundFile=Sound

uploadImage=Upload
uploadSoundFile=Upload

textSettings:=Text properties:
background:=Background:
color=Color
or=or
image=Image
deleteBackgroundImageBtn=
deleteBackgroundImageBtn.title=Delete image
imageDescription=Please enter a description of the picture
transparent=Transparent
opaque=Opaque
pairsToShow:=Amount of pairs:
pairSize:=Pair size:
small=Small
medium=Medium
large=Large
pairs:=Pairs:
myStudio=myStudio
pair=Pair
addPair=Add pair


# Alerts
incorrectFileSize=The size of the file is bigger than 1/2 Mega. Please reduce the size of the file or choose a different one.
incorrectFileType=The type of the file is not supported
uploadOnlyMp3=You can only upload a sound file of type mp3 

addSoundFileInRightFieldOfPair=Please add sound file pair-{{pairNumber}}
addImageFileInRightFieldOfPair=Please add image in pair-{{pairNumber}}
addTextInRightFieldOfPair=Please enter text in pair-{{pairNumber}}

addSoundFileInLeftFieldOfPair=Please add sound file in pair-{{pairNumber}}
addImageFileInLeftFieldOfPair=Please add image in pair-{{pairNumber}}
addTextInLeftFieldOfPair=Please enter text in pair-{{pairNumber}}

pairsNumberToShowIsTooBig=The number of pairs that you chose to show is greater than the number of pairs you entered 

minNumberOfPairs=Please enter at least {{minNumber}} of pairs

imageDescriptionError=Please enter a description of the picture: