# Hebrew translation
# vim: ft=jproperties

text=טקסט
image=תמונה
soundFile=קובץ שמע

uploadImage=העלו תמונה
uploadSoundFile=העלו קובץ שמע

textSettings:=הגדרות טקסט:
background:=רקע:
color=צבע
or=או
image=תמונה
deleteBackgroundImageBtn=
deleteBackgroundImageBtn.title=הסר תמונת רקע
imageDescription=הוסיפו תיאור לַתמונה:
transparent=שקוף
opaque=אטום
pairsToShow:=כמות הצמדים להצגה:
pairSize:=גודל הצמדים:
small=קטן
medium=בינוני
large=גדול
pairs:=צמדים:
myStudio=הסטודיו שלי
pair=צמד
addPair=הוספת צמד


# Alerts
incorrectFileSize=משקל התמונה גדול מ-1/2 מגה. יש להקטין את משקל התמונה או לבחור תמונה אחרת
incorrectFileType=סוג הקובץ לא נתמך
uploadOnlyMp3=ניתן להעלות קובץ שמע רק מסוג mp3

addSoundFileInRightFieldOfPair=אנא הזינו קובץ שמע בשדה הימני של צמד-{{pairNumber}}
addImageFileInRightFieldOfPair=אנא הזינו תמונה בשדה הימני של צמד-{{pairNumber}}
addTextInRightFieldOfPair=אנא הזינו טקסט בשדה הימני של צמד-{{pairNumber}}

addSoundFileInLeftFieldOfPair=אנא הזינו קובץ שמע בשדה השמאלי של צמד-{{pairNumber}}
addImageFileInLeftFieldOfPair=אנא הזינו תמונה בשדה השמאלי של צמד-{{pairNumber}}
addTextInLeftFieldOfPair=אנא הזינו טקסט בשדה השמאלי של צמד-{{pairNumber}}

pairsNumberToShowIsTooBig=מספר הצמדים שבחרתם להציג גדול ממספר הצמדים שהזנתם

minNumberOfPairs=נא הזינו לפחות {{minNumber}} צמדים

imageDescriptionError=הוסיפו תיאור לַתמונה