# Arabic translation
# vim: ft=jproperties

text=نصّ
image=صورة
soundFile=ملفّ صوتيّ

uploadImage=ارفعوا صورة
uploadSoundFile=ارفعوا ملفًّا صوتيًّا

textSettings:=ضبط النص:
background:=خلفيّة:
color=لون
or=أو
image=صورة
deleteBackgroundImageBtn=
deleteBackgroundImageBtn.title=إزالة صورة الخلفيّة
imageDescription=أضيفوا وصفًا للصورة
transparent=شفّاف
opaque=غير شفّاف
pairsToShow:=عدد الأزواج المعروضة:
pairSize:=حجم الأزواج:
small=صغير 
medium=متوسّط
large=كبير
pairs:=أزواج:
myStudio=الأستوديو الخاصّ بي
pair=زوج
addPair=إضافة زوج


# Alerts
incorrectFileSize=لا يمكن رفع ملفّات أكبر من 0ز5MB
incorrectFileType=نوع الملفّ غير مناسب
uploadOnlyMp3=يمكن تحميل ملفّ صوتي فقط من نوع mp3

addSoundFileInRightFieldOfPair= الرجاء إدخال ملفّ صوتي في الخانة اليمنى من الزوج{{pairNumber}}
addImageFileInRightFieldOfPair=الرجاء إدخال صورة في الخانة اليمنى من الزوج-{{pairNumber}}
addTextInRightFieldOfPair=الرجاء إدخال نصّ في الخانة اليمنى من الزوج-{{pairNumber}}

addSoundFileInLeftFieldOfPair=الرجاء إدخال ملفّ صوتيّ في الخانة اليسرى من الزوج-{{pairNumber}}
addImageFileInLeftFieldOfPair=الرجاء إدخال صورة في الخانة اليسرى من الزوج-{{pairNumber}}
addTextInLeftFieldOfPair=الرجاء إدخال نصّ في الخانة اليسرى من الزوج-{{pairNumber}}

pairsNumberToShowIsTooBig=عدد الأزواج التي اخترتم عرضها أكبر من عدد التي سجّلتموها

minNumberOfPairs=سجّلوا على الاقلّ {{minNumber}} أزواج

imageDescriptionError=أضيفوا وصفًا للصورة: