# Arabic translation
# vim: ft=jproperties

language:=اللغة:
hebrew=العبريّة
arabic=العربيّة

fontSize:=حجم الخط:
small=صغير
medium=متوسّط
large=كبير

numberOfStrikes:=عدد المحاولات الخاطئة:
noStrikes=لا محاولات خاطئة

numberOfWordsInBasket:=عدد الكلمات فيكلّ سلّة:
numberOfWordsAtSameTime:=عدد الكلمات التي تسقط في الوقت نفسه:
baskets:=سلال:
basket=سلّة
basketTitle=عنوان السلّة
basketInstruction=يجب إدخال مضمون مساوٍ لعدد الكلمات التي تمّ تحديدها.
addBasket=إضافة سلّة

deleteBtn=
deleteBtn.title=حذف

addWord=إضافة كلمة

# Alerts
inputTwoBasketsError=يجب إدخال سلّتين على الاقلّ
upToSixBasketsError=يمكن إدخال 6 سلال في الحدّ الاقصى
inputTitleError=يجب كتابة عنوان لكلّ السلال
missingTitleError=العنوان ناقص
notEnoughWordsError=تحتوي على عدد كلمات اقلّ من اللازم