# English translation
# vim: ft=jproperties

language:=language:
hebrew=Hebrew
arabic=Arabic

fontSize:=Font size:
small=Small
medium=Medium
large=Large

numberOfStrikes:=Number of strikes:
noStrikes=No strikes

numberOfWordsInBasket:=Number of words in every basket:
numberOfWordsAtSameTime:=Number of words falling at the same time:
baskets:=Baskets:
basket=Basket
basketTitle=Basket title
basketInstruction=Please enter content at least as much as the number of falling words that were defined.
addBasket=Add basket

deleteBtn=
deleteBtn.title=Delete
addWord=Add

# Alerts
inputTwoBasketsError=Please enter at least 2 baskets
upToSixBasketsError=You can enter up to six baskets
inputTitleError=Please enter a title for all the baskets
missingTitleError=Title missing
notEnoughWordsError=contains too few words