# Hebrew translation
# vim: ft=jproperties

language:=שפה:
hebrew=עברית
arabic=ערבית

fontSize:=גודל גופן:
small=קטן
medium=בינוני
large=גדול

numberOfStrikes:=מספר הפסילות:
noStrikes=ללא פסילות

numberOfWordsInBasket:=מספר מילים בכל סל:
numberOfWordsAtSameTime:=מספר מילים נופלות בו זמנית:
baskets:=סלים:
basket=סל
basketTitle=כותרת הסל
basketInstruction=יש להזין תכולה לפחות כמספר המילים הנופלות שהוגדרו.
addBasket=הוספת סל

deleteBtn=
deleteBtn.title=מחיקה

addWord=הוספת מילה

# Alerts
inputTwoBasketsError=יש להזין לפחות שני סלים
upToSixBasketsError=ניתן להזין עד שישה סלים
inputTitleError=יש להזין כותרת עבור כל הסלים
missingTitleError=חסר כותרת
notEnoughWordsError=מכיל מעט מדי מילים