# English translation
# vim: ft=jproperties

language:=ngôn ngữ:
hebrew=tiếng Hebrew
arabic=tiếng Ả Rập

fontSize:=Kích thước Font:
small=Nhỏ
medium=Vừa
large=Lớn

numberOfStrikes:=Số lần strike:
noStrikes=Không có lần strike nào

numberOfWordsInBasket:=Số lượng từ ở mỗi giỏ:
numberOfWordsAtSameTime:=Số lượng từ rơi xuống cùng một lúc:
baskets:=Các giỏ:
basket=Giỏ
basketTitle=Tên giỏ
basketInstruction=Xin nhập vào nội dung ít nhất là bằng số lượng từ rơi xuống đã được xác định.
addBasket=Thêm giỏ

deleteBtn=
deleteBtn.title=Xóa
addWord=Thêm

# Alerts
inputTwoBasketsError=Xin nhập vào ít nhất 2 giỏ
upToSixBasketsError=Bạn có thể nhập vào đến 6 giỏ
inputTitleError=Xin nhập vào tên cho tất cả các giỏ
missingTitleError=Thiếu tên
notEnoughWordsError=Chứa quá ít từ