# English translation
# vim: ft=jproperties

contentDirection:=Content flow:
rightToLeft=Right to Left
leftToRight=Left to Right
layout=Layout:
horizontal=Horizontal
vertical=Vertical
contentWidth=Content width:
variable= Variable (Example: Ordering words in a sentence)
uniform= Uniform (Example: Ordering images)
showFeedback=Display feedback:
items= Items:
addItem= Add item
deleteItem=Delete item

# Alerts
inputItemContent=No content was entered. Please add content or delete the item.
inputTwoItems=Please enter at least two items