# Vietnamese translation
# vim: ft=jproperties

contentDirection:=Hướng đi của nội dung:
rightToLeft=Phải sang Trái
leftToRight=Trái sang Phải
layout=Bố trí:
horizontal=Theo phương ngang
vertical=Theo phương thẳng đứng
contentWidth=Chiều rộng của nội dung:
variable= Có thể thay đổi (ví dụ: Sắp xếp từ trong một câu)
uniform= Đồng dạng (Ví dụ: sắp xếp hình ảnh)
showFeedback=Hiển thị phản hồi:
items= Các mục:
addItem= Thêm mục
deleteItem=Xoá mục

# Alerts
inputItemContent=Chưa có nội dung nhập vào. Xin hãy thêm nội dung hoặc xoá mục.
inputTwoItems=Xin nhập vào ít nhất 2 mục