# Hebrew translation
# vim: ft=jproperties

contentDirection:=اتّجاه المضمون:
rightToLeft=من اليمين إلى اليسار
leftToRight=من اليسار إلى اليمين
layout=انتشار:
horizontal=أفقيّ
vertical=عموديّ
contentWidth=عرض المضمون:
variable=متغيّر (مثلًا: ترتيبالكلمات في الجملة )
uniform=متجاس (مثلًا: ترتيب صور لعدد من الخطوات)
showFeedback=عرض مردود االانتهاء:
items=موادّ:
addItem=إضافة مادّة
deleteItem=حذف خيار
font-family=اسم الخط:

# Alerts
inputItemContent=الرجاء كتابة المضمون في المادّة
inputTwoItems=الرجاء إدخال مادتيّن على الاقلّ