# Hebrew translation
# vim: ft=jproperties

contentDirection:=כיוון התוכן:
rightToLeft=מימין לשמאל
leftToRight=משמאל לימין
layout=פריסה:
horizontal=אופקית
vertical=אנכית
contentWidth=רוחב התוכן:
variable=משתנה (דוגמא: סידור מילים למשפט)
uniform=אחיד (דוגמא: סידור תמונות)
showFeedback=הצגת משוב:
items=פריטים:
addItem=הוספת פריט
deleteItem=מחיקת פריט

# Alerts
inputItemContent=נא להזין תוכן בפריטים
inputTwoItems=נא להזין לפחות 2 פריטים