# English translation
# vim: ft=jproperties

general=general
workSurface=work surface
contentDirection:=content direction:
rightToLeft=right to left 
leftToRight=left to right 

hotspotView:=Hotspot:
withNumber=With number 
emptySquare=Without number
backgroundImage:=Image:
uploadImage=Upload
modeHotspots=Hotspots
modeVieport=Focus area
parameters=Properties
correctAnswer=Correct answer 
wrongAnswer=Wrong answer 
info=Information 
link=Link
width=Width
height=Height
size=Size of window:

linkDescription=Please enter a descritpion for the links:
backgroundDescription=Please enter a description of the picture:

feedback=Feedback 
deleteHotspot=Delete Hotspot
deleteViewport=Delete focus area
createNewHotspotMessage=Click on the image to create a hotspot and select it to set the properties 
createNewViewportMessage=Click on the image to create a focus area and drag the rectangle borders to set its size
myStudio=myStudio 
deleteAllHotspots?=Unused

# Alerts
inputContentError=No content was entered. Please add content or delete the item.
uploadImageError=Please upload an image.
imageDescriptionError=Please enter a description of the picture.
inputInfoTextError=Please enter the content text.
inputCorrectAnswerError=Please enter the correct answer.

inputLinkTextError=Please enter the link address.
inputLinkDescriptionError=Please enter a descritpion for the links
inputLinkWidthError=Please enter the correct width.
inputlINKHeightError=Please enter the correct height.

imageSizeIsTooBig=The size of the image is bigger than 1 MB. Please reduce the size of the file or choose a different one.