# Hebrew translation
# vim: ft=jproperties

general=כללי
workSurface=משטח העבודה
contentDirection:=כיוון התוכן:
rightToLeft=מימין לשמאל
leftToRight=משמאל לימין

hotspotView:=תצוגת התשובה:
withNumber=עם מספר
emptySquare=ללא מספר
backgroundImage:=תמונת רקע:
uploadImage=העלו תמונה
modeHotspots=תשובות
modeVieport=חלונית מיקוד
parameters=מאפיינים
correctAnswer=תשובה נכונה
wrongAnswer=תשובה שגויה
info=מידע
link=קישור
width=רוחב
height=גובה
size=גודל חלונית:

linkDescription= הוסיפו תיאור לַקישור
backgroundDescription= הוסיפו תיאור לַתמונה:

feedback=חיווי
deleteHotspot=מחיקת תשובה
deleteViewport=מחיקת חלונית המיקוד
createNewHotspotMessage=לחצו בכל איזור בתמונה כדי ליצור תשובה חדשה. לחצו על התשובה שנוצרה כדי לשנות את המאפיינים שלה. 
createNewViewportMessage=לחצו בכל איזור בתמונה כדי ליצור חלונית מיקוד חדשה.
myStudio=הסטודיו שלי
deleteAllHotspots?=Not used

# Alerts
inputContentError=אנא הזינו תוכן בתבנית או מחקו את הפריט.
uploadImageError=אנא העלו תמונה.
imageDescriptionError=הוסיפו תיאור לַתמונה
inputInfoTextError=אנא הזינו את טקסט המידע.
inputCorrectAnswerError=אנא בחרו את התשובה הנכונה.

inputLinkTextError=אנא הזינו את טקסט הקישור.
inputLinkDescriptionError= הוסיפו תיאור לַקישור
inputLinkWidthError=אנא הזינו את רוחב החלונית.
inputlINKHeightError=אנא הזינו את גובה החלונית.

imageSizeIsTooBig=משקל התמונה גדול מ-1 מגה. יש להקטין את משקל התמונה או לבחור תמונה אחרת.