# Vietnamese Translation
# vim: ft=jproperties

general=Tổng thể
workSurface=Vùng thao tác
contentDirection:=chiều của nội dung:
rightToLeft=phải sang trái 
leftToRight=trái sang phải

hotspotView:=Hotspot:
withNumber=Với số 
emptySquare=Không có số
backgroundImage:=Ảnh:
uploadImage=Tải lên
modeHotspots=Hotspots
modeVieport=Vùng tập trung
parameters=Thuộc tính
correctAnswer=Đáp án đúng 
wrongAnswer=Đáp án sai
info=Thông tin
feedback=Phản hồi 
deleteHotspot=Xoá Hotspot
deleteViewport=Xoá vùng tập trung
createNewHotspotMessage=Nhấn vào ảnh để tạo một hotspot và chọn nó để thiết lập thuộc tính 
createNewViewportMessage=Nhấp vào ảnh để tạo ra một vùng tập trung và kéo biên của hình chữ nhật để đặt lại kích thước
myStudio=Studio của tôi 
deleteAllHotspots?=Chưa sử dụng

# Alerts
inputContentError=Chưa có nội dung nhập vào. Xin thêm vào nội dung hoặc xoá mục.
uploadImageError=Xin tải lên một ảnh.
inputInfoTextError=Xin nhập vào chữ của nội dung.
inputCorrectAnswerError=Xin nhập vào đáp án đúng.

imageSizeIsTooBig=Kích thước của ảnh lớn hơn 1/2 Mega. Xin giảm kích thước của tập tin hoặc chọn tập tin khác.