# Arabic translation
# vim: ft=jproperties

contentDirection:=اتّجاه المضمون:
rightToLeft=من اليمين غلى اليسار
leftToRight=من اليسار إلى اليمين

hotspotView:=عرض Hotspot:
withNumber=مع رقم
emptySquare=مربّع فارغ
backgroundImage:=صورة خلفيّة:
uploadImage=ارفعوا صورة
modeHotspots=خيارات
modeVieport=مجال التركيز
parameters=معايير
correctAnswer=إجابة صحيحة
wrongAnswer=إجابة خاطئة
info=معلومات
link=الرابط
width=عرض
height=ارتفاع
size=الشباك حجم:

linkDescription=أضيفوا وصفًا للرابط
backgroundDescription=أضيفوا وصفًا للصورة

feedback=مردود
deleteHotspot=حذف Hotspot
deleteViewport=حذف مجال التركيز
createNewHotspotMessage=انقروا على كل منطقة في الصورة لإنشاء hotspot جديدة واختاروها لضبط الـ
createNewViewportMessage=انقر على الصورة لإنشاء منطقة التركيز واسحب حدود المستطيل لضبط حجمها
myStudio=الاستوديو الخاصّ بي
deleteAllHotspots?=هل توّد حذف جميع الرموز؟ 

# Alerts
inputContentError=الرجاء إدخال المضمون.
uploadImageError=الرجاء رفع الصورة.
imageDescriptionError=أضيفوا وصفًا للصورة
inputInfoTextError=الرجاء إدخال نصّ المعلومات.
inputCorrectAnswerError=الرجاء تسجيل الإجابة الصحيحة.

inputLinkTextError=الرجاء إدخال نصّ الرابط.
inputLinkDescriptionError=أضيفوا وصفًا للرابط
inputLinkWidthError=الرجاء إدخال عرض الشباك.
inputlINKHeightError=الرجاء إدخال ارتفاع الشباك.


imageSizeIsTooBig=حجم الصورة أكبر من 1 ميغا. يجب تصغير حجم الصورة أو اختيار صورة جديدة
